<?php

namespace Omnipay\NetCash\Message;

use Omnipay\Common\Message\AbstractResponse;
use Illuminate\Support\Arr;

/**
 * Class CompletePurchaseResponse
 * @package Omnipay\NetCash\Message
 */
class CompletePurchaseResponse extends AbstractResponse
{
    /**
     * Indicates whether transaction was successful
     * @return bool
     */
    public function isSuccessful()
    {
        return !empty($this->data['success']);
    }

    /**
     * Get transaction ID, generated by merchant
     * @return mixed|string
     */
    public function getTransactionId()
    {
        return Arr::get($this->data, 'Reference');
    }

    /**
     * Get transaction reference, generated by gateway
     * @return mixed|null|string
     */
    public function getTransactionReference()
    {
        return Arr::get($this->data, 'RequestTrace');
    }
}